### ISSUE TITLE
პროექტის რედაქტირება

### ISSUE THREAD

**Issue by zgnachvi** [sosoxuc/personal-finances#2]
პროექტის რედაქტირების დროს თუ არ შეცვალა სახელი, დადიზეიბლებული იყოს შენხვის ღილაკი
-ჩემი აზრით პეწიას მატებს ამ პატარა ფორმას

**Comment by sosoxuc** [comment]
ნიკოლოზ ეხლა კარგად მითხარი აქ რა უნდა ვქნათ
