### ISSUE TITLE
გეგმიური ტრანზაქციების ჩასმა მიმდევრობით -ბექი არის, გასაკეთებელია წინა მხარე

### ISSUE THREAD

**Issue by zgnachvi** [sosoxuc/personal-finances#34]
/transactions/createMultiple
intervalType, (დღე - 1, თვე - 2, წელი - 3)
intervalTypeValue(int value),
dateFrom,
dateTo

**Comment by sosoxuc** [comment]
დავამატე კვირა(4), გთხოვ გაითვალისწინო
